name = "WeilFirstPrime"
version = "0.1.0"
defaultTargets = ["WeilFirstPrime"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.32.2"

[[lean_lib]]
name = "WeilFirstPrime"
